const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.bound,
		C3.Plugins.TiledBg,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.Keyboard,
		C3.Behaviors.scrollto,
		C3.Behaviors.Sin,
		C3.Plugins.Audio,
		C3.Plugins.Particles,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Spritefont2,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Behaviors.scrollto.Cnds.IsEnabled,
		C3.Plugins.Text.Acts.SetX,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.EightDir.Acts.SetIgnoreInput,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Exps.X,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.System.Cnds.CompareTime,
		C3.Plugins.System.Cnds.EveryTick
	];
};
self.C3_JsPropNameTable = [
	{"8Direction": 0},
	{BoundToLayout: 0},
	{S_Hero: 0},
	{BG_Scene1: 0},
	{BG_Sky: 0},
	{Obj_Build: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{S_Bullet: 0},
	{Keyboard: 0},
	{TiledBackground: 0},
	{TiledBackground2: 0},
	{ScrollTo: 0},
	{Camera: 0},
	{Moon: 0},
	{Sine: 0},
	{S_Enemy: 0},
	{Audio: 0},
	{Particles: 0},
	{Explosion: 0},
	{S_Bullet_enemy: 0},
	{Boss: 0},
	{Instructions: 0},
	{Anchor: 0},
	{SCORE: 0},
	{ScoreSprite: 0},
	{HEALTH: 0},
	{BosTH: 0},
	{Score: 0},
	{Health: 0},
	{BossHealth: 0}
];

self.InstanceType = {
	S_Hero: class extends self.ISpriteInstance {},
	BG_Scene1: class extends self.ITiledBackgroundInstance {},
	BG_Sky: class extends self.ITiledBackgroundInstance {},
	Obj_Build: class extends self.ITiledBackgroundInstance {},
	S_Bullet: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Camera: class extends self.ISpriteInstance {},
	Moon: class extends self.ISpriteInstance {},
	S_Enemy: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Particles: class extends self.IParticlesInstance {},
	Explosion: class extends self.ISpriteInstance {},
	S_Bullet_enemy: class extends self.ISpriteInstance {},
	Boss: class extends self.ISpriteInstance {},
	Instructions: class extends self.ITextInstance {},
	SCORE: class extends self.ITextInstance {},
	ScoreSprite: class extends self.ISpriteFontInstance {},
	HEALTH: class extends self.ITextInstance {},
	BosTH: class extends self.ITextInstance {}
}