const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.bound,
		C3.Plugins.TiledBg,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.Keyboard,
		C3.Behaviors.scrollto,
		C3.Behaviors.Sin,
		C3.Plugins.Audio,
		C3.Plugins.Particles,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Exps.AnimationName
	];
};
self.C3_JsPropNameTable = [
	{"8Direction": 0},
	{BoundToLayout: 0},
	{S_Hero: 0},
	{BG_Scene1: 0},
	{BG_Sky: 0},
	{Obj_Build: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{S_Bullet: 0},
	{Keyboard: 0},
	{TiledBackground: 0},
	{TiledBackground2: 0},
	{ScrollTo: 0},
	{Camera: 0},
	{Moon: 0},
	{Sine: 0},
	{S_Enemy: 0},
	{Audio: 0},
	{Particles: 0},
	{Explosion: 0},
	{S_Bullet_enemy: 0}
];

self.InstanceType = {
	S_Hero: class extends self.ISpriteInstance {},
	BG_Scene1: class extends self.ITiledBackgroundInstance {},
	BG_Sky: class extends self.ITiledBackgroundInstance {},
	Obj_Build: class extends self.ITiledBackgroundInstance {},
	S_Bullet: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Camera: class extends self.ISpriteInstance {},
	Moon: class extends self.ISpriteInstance {},
	S_Enemy: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Particles: class extends self.IParticlesInstance {},
	Explosion: class extends self.ISpriteInstance {},
	S_Bullet_enemy: class extends self.ISpriteInstance {}
}